title = "默风博客"
theme = "hugo-theme-flat"
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 4
baseURL = "https://blog.mofeng.run"


[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'monokailight'
tabWidth = 4


[[menus.main]]
pageref = "/"
name = "首页"
weight = 1

[[menus.main]]
name = "文章"
url = "/posts/"
weight = 2

[[menus.main]]
pageref = "/projects"
name = "项目"
weight = 3

[[menus.main]]
pageref = "/about"
name = "关于"
weight = 4

[params]
description = "愿逐梦千里，双眸不染一尘。"
mainSections = ['posts']

# you can set multi row of footers like these
[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Creative Commons Attribution 4.0 International"
url = "https://creativecommons.org/licenses/by/4.0/"
pre = "Copyright <a href=\"https://creativecommons.org/licenses/by/4.0/\">CC BY-4.0</a>"

[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Hugo"
url = "https://gohugo.io"
pre = "Powered by <a href=\"https://gohugo.io\">Hugo</a>"
[[params.footer_rows.items]]
name = "theme flat"
url = "https://cgit.leafee98.com/hugo-theme-flat.git"
pre = "Theme <a href=\"https://git.leafee98.com/leafee98/hugo-theme-flat.git\">hugo-theme-flat</a>"