name: Deploy Hugo

on:
  push:
    branches:
      - master
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Clone Hugo Theme
        run: git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1

      - name: Build 
        run: hugo

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          commit_message: "Deploy Hugo site to gh-pages"
